// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irhxtupdvcpocjnzawrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyaHh0dXBkdmNwb2Nqbnphd3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNjg3NDUsImV4cCI6MjA1Mzg0NDc0NX0.flx9gqN7aCn07j_RUeBb0hVbyYNRyTozIjQO303OvTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);